---
redisCluster:
  clusterSize: 3
  clusterVersion: v7
  persistenceEnabled: true
  image: registry:5000/opstree/redis #quay.io/opstree/redis
  tag: v7.0.5
  imagePullPolicy: IfNotPresent
  redisSecret:
    secretName: redis-secret
    secretKey: password
    secretValue: amarsoft
  leader:
    replicas: 3
    serviceType: ClusterIP
    affinity: {}
      # nodeAffinity:
      #   requiredDuringSchedulingIgnoredDuringExecution:
      #     nodeSelectorTerms:
      #     - matchExpressions:
      #       - key: disktype
      #         operator: In
      #         values:
      #         - ssd
  follower:
    replicas: 3
    serviceType: ClusterIP
    affinity: {}
      # nodeAffinity:
      #   requiredDuringSchedulingIgnoredDuringExecution:
      #     nodeSelectorTerms:
      #     - matchExpressions:
      #       - key: disktype
      #         operator: In
      #         values:
      #         - ssd
  resources: 
    requests:
     cpu: '4'
     memory: 8Gi
    limits:
     cpu: '8'
     memory: 16Gi

# labels:
#   foo: bar
#   test: echo

pdb:
  enabled: false
  maxUnavailable: 1

externalConfig:
  enabled: false
  data: |
    tcp-keepalive 400
    slowlog-max-len 158
    stream-node-max-bytes 2048
    Maxmemory-policy allkeys-lru
    stop-writes-on-bgsave-error no

externalService:
  enabled: false
  # annotations:
  #   foo: bar
  serviceType: LoadBalancer
  port: 6379

serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 10s
  namespace: monitoring

redisExporter:
  enabled: true
  image: registry:5000/opstree/redis-exporter
  tag: "v1.44.0"
  imagePullPolicy: IfNotPresent
  resources: {}
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
    # limits:
    #   cpu: 100m
    #   memory: 128Mi

sidecars: []
  # - name: "sidecar1"
  #   image: "image:1.0"
  #   imagePullPolicy: Always
  #   resources:
  #     limits:
  #       cpu: 50m
  #       memory: 64Mi
  #     requests:
  #       cpu: 10m
  #       memory: 32M
  #   env:
  #   - name: VAR_NAME
  #     value: "value1"

# priorityClassName: "-"

nodeSelector: {}
  # memory: medium

storageSpec:
  volumeClaimTemplate:
    spec:
      storageClassName: local-storage
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
  #   selector: {}

securityContext:
  runAsUser: 1000
  fsGroup: 1000

affinity: {}
  # nodeAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: disktype
  #         operator: In
  #         values:
  #         - ssd

# serviceAccountName: redis-sa

# TLS:
#   ca: ca.key
#   cert: tls.crt
#   key: tls.key
#   secret:
#     secretName: redis-tls-cert
