---
apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-cm
  namespace: kubemate-opt
data:
  NAMESRV_ADDR: nameserver-0.nameserver-headless:9876;nameserver-1.nameserver-headless:9876
  broker-0.conf: |
    brokerClusterName = RaftCluster
    brokerName=broker-01
    listenPort=30911
    storePathRootDir=/data/rmqstore/node
    storePathCommitLog=/data/rmqstore/node/commitlog
    enableDLegerCommitLog=true
    dLegerGroup=RaftNode00
    dLegerPeers=n1-broker-0.broker-headless:40911;n2-broker-1.broker-headless:40911;n3-broker-2.broker-headless:40911
    ## must be unique
    dLegerSelfId=n1
    sendMessageThreadPoolNums=16
  broker-1.conf: |
    brokerClusterName = RaftCluster
    brokerName=broker-02
    listenPort=30911
    storePathRootDir=/data/rmqstore/node
    storePathCommitLog=/data/rmqstore/node/commitlog
    enableDLegerCommitLog=true
    dLegerGroup=RaftNode00
    dLegerPeers=n1-broker-0.broker-headless:40911;n2-broker-1.broker-headless:40911;n3-broker-2.broker-headless:40911
    ## must be unique
    dLegerSelfId=n2
    sendMessageThreadPoolNums=16
  broker-2.conf: |
    brokerClusterName = RaftCluster
    brokerName=broker-03
    listenPort=30911
    storePathRootDir=/data/rmqstore/node
    storePathCommitLog=/data/rmqstore/node/commitlog
    enableDLegerCommitLog=true
    dLegerGroup=RaftNode00
    dLegerPeers=n1-broker-0.broker-headless:40911;n2-broker-1.broker-headless:40911;n3-broker-2.broker-headless:40911
    ## must be unique
    dLegerSelfId=n3
    sendMessageThreadPoolNums=16
---
###headless
apiVersion: v1
kind: Service
metadata:
  labels:
    app: broker-headless
  name: broker-headless
  namespace: kubemate-opt
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - name: broker
      port: 3911
      protocol: TCP
      targetPort: 30911
    - name: test
      port: 30909
      protocol: TCP
      targetPort: 30909
    - name: raft
      port: 40911
      protocol: TCP
      targetPort: 40911
  selector:
    app: broker
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: broker
  name: broker
  namespace: kubemate-opt
spec:
  replicas: 3
  serviceName: broker-headless
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: broker
                topologyKey: kubernetes.io/hostname
              weight: 100
      initContainers:
        - name: init-statefulset
          image: 38.62.44.40:5000/busybox/busybox:1.30
          command:
            - sh
            - "-c"
            - |
              set -ex
              ordinal=`echo $HOSTNAME | awk -F '-' '{print $NF}'`
              cp /mnt/configmap/broker-$ordinal.conf /opt/conf/broker.conf
          volumeMounts:
            - name: conf
              mountPath: /opt/conf
            - name: broker-config
              mountPath: /mnt/configmap
      containers:
        - command:
            - sh
            - mqbroker
            - '-c'
            - /opt/conf/broker.conf
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: NAMESRV_ADDR
              valueFrom:
                configMapKeyRef:
                  name: broker-cm
                  key: NAMESRV_ADDR
          image: 38.62.44.40:5000/rocketmq/rocketmq:4.9.2 
          imagePullPolicy: IfNotPresent
          name: broker
          ports:
            - containerPort: 30911
              name: broker
              protocol: TCP
            - containerPort: 30909
              name: test
              protocol: TCP
            - containerPort: 40911
              name: raft
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/conf
              name: conf
            - mountPath: /data/rmqstore/node
              name: store
          resources:
            requests:
              cpu: 2
              memory: 8Gi
            limits:
              cpu: 2
              memory: 8Gi 
      volumes:
        - configMap:
            name: broker-cm
          name: broker-config
        - name: conf
          emptyDir: { }
  volumeClaimTemplates:
    - metadata:
        name: store
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: managed-nfs-storage
        resources:
          requests:
            storage: 50Gi
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq-dashbord
  namespace: kubemate-opt
  labels:
    app: rocketmq-dashbord
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-dashbord
  template:
    metadata:
      labels:
        app: rocketmq-dashbord
    spec:
      containers:
        - name: web-nameserver
          image: 38.62.44.40:5000/rocketmq/rocketmq-console-ng:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_OPTS
              value: '-Drocketmq.namesrv.addr=nameserver-0.nameserver-headless:9876;nameserver-1.nameserver-headless:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false'
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 4024Mi
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /etc/localtime
              name: timezone
              readOnly: true
      volumes:
        - name: timezone
          hostPath:
            path: /etc/localtime
---
apiVersion: v1
kind: Service
metadata:
  name: rocketmq-dashbord
  namespace: kubemate-opt
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31330
  selector:
    app: rocketmq-dashbord
---
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nameserver
  namespace: kubemate-opt
spec:
  selector:
    matchLabels:
      app: nameserver
  replicas: 2
  serviceName: nameserver-headless
  template:
    metadata:
      labels:
        app: nameserver
    spec:
      containers:
        - command:
            - sh
            - mqnamesrv
          env:
            - name: TZ
              value: Asia/Shanghai
          image: 38.62.44.40:5000/rocketmq/rocketmq:4.9.2
          imagePullPolicy: IfNotPresent
          name: nameserver
          ports:
            - containerPort: 9876
              name: nameserver
              protocol: TCP
          resources:
            requests:
              cpu: 2
              memory: 1Gi
            limits:
              cpu: 2
              memory: 2Gi              
---
##service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nameserver-svc
  name: nameserver-svc
  namespace: kubemate-opt
spec:
  ports:
    - name: nameserver
      port: 9876
      protocol: TCP
      targetPort: 9876
  selector:
    app: nameserver
  type: ClusterIP
---
##headless
apiVersion: v1
kind: Service
metadata:
  name: nameserver-headless
  namespace: kubemate-opt
  labels:
    app: nameserver-headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: nameserver
      port: 9876
      protocol: TCP
      targetPort: 9876
  selector:
    app: nameserver
