---
redisOperator:
  name: redis-operator
  imageName: 38.62.44.40:5000/opstree/redis-operator
  # Overrides the image tag whose default is the chart appVersion.
  imageTag: ""
  imagePullPolicy: IfNotPresent

  # Additional pod annotations
  podAnnotations: {}
  # Additional Pod labels (e.g. for filtering Pod by custom labels)
  podLabels: {}

# watch_namespace: ot-operators

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 200Mi

replicas: 1

serviceAccountName: redis-operator

priorityClassName: ""
nodeSelector: {}
tolerateAllTaints: false
tolerations: []
affinity: {}
