apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubemate-system
resources:
  - tenant.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/managed-by: kubefoundry
secretGenerator:
  - name: kubemate-minio-env
    files:
      - config.env=tenant.env
