ALTER TABLE clusters
    ADD COLUMN kubemate_enabled BOOLEAN DEFAULT FALSE NOT NULL;

ALTER TABLE cluster_components
    ADD COLUMN config_json CLOB DEFAULT '{}' NOT NULL;

UPDATE cluster_components target
SET enabled = CASE
    WHEN target.enabled = TRUE
      OR EXISTS (
          SELECT 1
          FROM cluster_components legacy
          WHERE legacy.cluster_id = target.cluster_id
            AND legacy.component_key = 'loki'
            AND legacy.enabled = TRUE
      ) THEN TRUE
    ELSE FALSE
END
WHERE target.component_key = 'storage_observability';

DELETE FROM cluster_components legacy
WHERE legacy.component_key = 'loki'
  AND EXISTS (
      SELECT 1
      FROM cluster_components target
      WHERE target.cluster_id = legacy.cluster_id
        AND target.component_key = 'storage_observability'
  );

UPDATE cluster_components
SET component_key = 'storage_observability'
WHERE component_key = 'loki';

INSERT INTO cluster_components (cluster_id, component_key, enabled)
SELECT clusters.id, 'nfs', FALSE
FROM clusters
WHERE NOT EXISTS (
    SELECT 1 FROM cluster_components
    WHERE cluster_components.cluster_id = clusters.id
      AND cluster_components.component_key = 'nfs'
)
UNION ALL
SELECT clusters.id, 'kubemate', FALSE
FROM clusters
WHERE NOT EXISTS (
    SELECT 1 FROM cluster_components
    WHERE cluster_components.cluster_id = clusters.id
      AND cluster_components.component_key = 'kubemate'
)
UNION ALL
SELECT clusters.id, 'traefik', FALSE
FROM clusters
WHERE NOT EXISTS (
    SELECT 1 FROM cluster_components
    WHERE cluster_components.cluster_id = clusters.id
      AND cluster_components.component_key = 'traefik'
)
UNION ALL
SELECT clusters.id, 'storage_observability', FALSE
FROM clusters
WHERE NOT EXISTS (
    SELECT 1 FROM cluster_components
    WHERE cluster_components.cluster_id = clusters.id
      AND cluster_components.component_key = 'storage_observability'
)
UNION ALL
SELECT clusters.id, 'prometheus', FALSE
FROM clusters
WHERE NOT EXISTS (
    SELECT 1 FROM cluster_components
    WHERE cluster_components.cluster_id = clusters.id
      AND cluster_components.component_key = 'prometheus'
)
UNION ALL
SELECT clusters.id, 'redis_sentinel', FALSE
FROM clusters
WHERE NOT EXISTS (
    SELECT 1 FROM cluster_components
    WHERE cluster_components.cluster_id = clusters.id
      AND cluster_components.component_key = 'redis_sentinel'
);

CREATE TABLE cluster_component_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cluster_id BIGINT NOT NULL,
    component_key VARCHAR(64) NOT NULL,
    status VARCHAR(32) DEFAULT 'not_installed' NOT NULL,
    installed_version VARCHAR(64),
    last_job_id BIGINT,
    last_error_code VARCHAR(128),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cluster_component_states_cluster
        FOREIGN KEY (cluster_id) REFERENCES clusters (id) ON DELETE CASCADE,
    CONSTRAINT fk_cluster_component_states_job
        FOREIGN KEY (last_job_id) REFERENCES jobs (id) ON DELETE SET NULL,
    CONSTRAINT uk_cluster_component_states_cluster_key UNIQUE (cluster_id, component_key),
    CONSTRAINT ck_cluster_component_states_status
        CHECK (status IN ('not_installed', 'installing', 'installed', 'failed'))
);

CREATE INDEX idx_cluster_component_states_job
    ON cluster_component_states (last_job_id);

INSERT INTO cluster_component_states (cluster_id, component_key, status)
SELECT cluster_id, component_key, 'not_installed'
FROM cluster_components;

UPDATE clusters
SET kubemate_enabled = TRUE
WHERE EXISTS (
    SELECT 1
    FROM cluster_components
    WHERE cluster_components.cluster_id = clusters.id
      AND cluster_components.enabled = TRUE
);
