ALTER TABLE clusters ADD COLUMN description VARCHAR(512) DEFAULT '' NOT NULL;
ALTER TABLE clusters ADD COLUMN pod_subnet VARCHAR(64) DEFAULT '' NOT NULL;
ALTER TABLE clusters ADD COLUMN service_subnet VARCHAR(64) DEFAULT '' NOT NULL;
ALTER TABLE clusters ADD COLUMN registry_hostname VARCHAR(128) DEFAULT '' NOT NULL;
ALTER TABLE clusters ADD COLUMN registry_ip VARCHAR(64) DEFAULT '' NOT NULL;
ALTER TABLE clusters ADD COLUMN registry_port INTEGER DEFAULT 5000 NOT NULL;
ALTER TABLE clusters ADD COLUMN node_config_version BIGINT DEFAULT 0 NOT NULL;
ALTER TABLE clusters ADD COLUMN node_test_status VARCHAR(32) DEFAULT 'pending' NOT NULL;

ALTER TABLE nodes ADD COLUMN ipv6 VARCHAR(128) DEFAULT '' NOT NULL;
ALTER TABLE nodes ADD COLUMN password_ciphertext CLOB;
ALTER TABLE nodes ADD COLUMN password_iv VARCHAR(64);
ALTER TABLE nodes ADD COLUMN password_version INTEGER;
ALTER TABLE nodes ADD COLUMN is_draft BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE nodes ADD COLUMN node_test_status VARCHAR(32) DEFAULT 'pending' NOT NULL;
ALTER TABLE nodes ADD COLUMN host_fingerprint VARCHAR(256);
ALTER TABLE nodes ADD COLUMN os_type VARCHAR(128);
ALTER TABLE nodes ADD COLUMN os_version VARCHAR(128);
ALTER TABLE nodes ADD COLUMN architecture VARCHAR(64);
ALTER TABLE nodes ADD COLUMN node_test_message VARCHAR(1024);

ALTER TABLE nodes ALTER COLUMN host DROP NOT NULL;
ALTER TABLE nodes ALTER COLUMN name DROP NOT NULL;
