ALTER TABLE clusters ADD COLUMN kubernetes_work_dir VARCHAR(512) DEFAULT '/data/k8s_install' NOT NULL;
ALTER TABLE clusters ADD COLUMN image_registry_type VARCHAR(32) DEFAULT 'REGISTRY' NOT NULL;

CREATE TABLE node_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id BIGINT NOT NULL,
    role VARCHAR(32) NOT NULL,
    CONSTRAINT fk_node_roles_node
        FOREIGN KEY (node_id) REFERENCES nodes (id) ON DELETE CASCADE,
    CONSTRAINT uk_node_roles_node_role UNIQUE (node_id, role)
);

INSERT INTO node_roles (node_id, role)
SELECT id, node_role
FROM nodes
WHERE node_role IS NOT NULL
  AND TRIM(node_role) <> '';

INSERT INTO node_roles (node_id, role)
SELECT n.id, 'registry'
FROM nodes n
JOIN clusters c ON c.id = n.cluster_id
WHERE c.registry_ip IS NOT NULL
  AND TRIM(c.registry_ip) <> ''
  AND n.host = c.registry_ip
  AND NOT EXISTS (
      SELECT 1
      FROM node_roles existing_role
      WHERE existing_role.node_id = n.id
        AND existing_role.role = 'registry'
  );

CREATE TABLE cluster_components (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cluster_id BIGINT NOT NULL,
    component_key VARCHAR(64) NOT NULL,
    enabled BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cluster_components_cluster
        FOREIGN KEY (cluster_id) REFERENCES clusters (id) ON DELETE CASCADE,
    CONSTRAINT uk_cluster_components_cluster_key UNIQUE (cluster_id, component_key)
);

CREATE TABLE installation_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    cluster_id BIGINT NOT NULL,
    snapshot_json CLOB NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_installation_snapshots_job
        FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE CASCADE,
    CONSTRAINT fk_installation_snapshots_cluster
        FOREIGN KEY (cluster_id) REFERENCES clusters (id) ON DELETE CASCADE,
    CONSTRAINT uk_installation_snapshots_job UNIQUE (job_id)
);

UPDATE clusters
SET installation_locked = FALSE
WHERE installation_locked = TRUE
  AND NOT EXISTS (
      SELECT 1
      FROM jobs
      WHERE jobs.cluster_id = clusters.id
        AND jobs.job_type = 'install'
        AND jobs.status = 'success'
  );
