apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-ha-0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeclaim
    name: data-redis-ha-server-0
    namespace: redis-sentinel
  local:
    path: /data/redis-sentinel
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k8sw1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-redis-ha-server-0
  namespace: redis-sentinel
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: pvc-ha-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-ha-1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeclaim
    name: data-redis-ha-server-1
    namespace: redis-sentinel
  local:
    path: /data/redis-sentinel
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k8sw2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-redis-ha-server-1
  namespace: redis-sentinel
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: pvc-ha-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-ha-2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeclaim
    name: data-redis-ha-server-2
    namespace: redis-sentinel
  local:
    path: /data/redis-sentinel
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k8sw3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-redis-ha-server-2
  namespace: redis-sentinel
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: pvc-ha-2
